spring:
  application:
    name: order
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848 # nacos 服务端地址
server:
  port: 8082

feign:
  httpclient:
    enabled: true #支持HTTPClient
    max-connections: 200 #最大连接数
    max-connections-per-route: 50 #单个路径的最大连接数